server:
  port: 8088
spring:
  application:
    name: beStrong
  datasource:
    url: jdbc:postgresql://localhost:5432/dbo_be_strong
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect